### ISSUE TITLE
example of  chapter 9, page 2 pdf 

### ISSUE THREAD

**Issue by stardustman** [remzi-arpacidusseau/ostep-homework#12]
Hello, I read the chapter [9 cpu-sched-lottery](http://pages.cs.wisc.edu/~remzi/OSTEP/cpu-sched-lottery.pdf) page 2,

    Here is an example output of a lottery scheduler’s winning tickets:
        63 85 70 39 76 17 29 41 36 39 10 99 68 83 63 62 43 0 49. 
        Here is the resulting schedule:
        A   A   A     A   A   A   A   A   A       A        A   A   A   A   A
          B         B                          B       B

 I find the number of tickets is `19`, not `20`.
the description below the example use the number of tickets is 20. which is 
"In our example above, B only get to run 4 our of `20` time slices(20%), instead of the desired 25% allocation." 
the example may miss a ticket for `A`.

**Comment by remzi-arpacidusseau** [comment]
thanks, fixed!

**Comment by remzi-arpacidusseau** [comment]
(p.s. this should be done on "ostep-typos" not "ostep-homework")
