### ISSUE TITLE
when i execute process-run.py in shell, there is a problem.

### ISSUE THREAD

**Issue by johnmaster** [remzi-arpacidusseau/ostep-homework#23]
for example 
moocos-> python3 process-run.py -l 3:0 -L 5 -c -p
Time    PID: 0       CPU       IOs
  1     RUN:io         1          
  2    WAITING                   1
  3    WAITING                   1
  4    WAITING                   1
  5    WAITING                   1
  6*    RUN:io         1          
  7    WAITING                   1
  8    WAITING                   1
  9    WAITING                   1
 10    WAITING                   1
 11*    RUN:io         1          
 12    WAITING                   1
 13    WAITING                   1
 14    WAITING                   1
 15    WAITING                   1
 16*      DONE         1
Stats: Total Time 16
Stats: CPU Busy 4 (25.00%)
Stats: IO Busy  12 (75.00%)

why 16rows output 1 in CPU cols? The cpu Busy is not equal to  18.75%.

**Comment by remzi-arpacidusseau** [comment]
Updated the simulator generally not to have this issue. thanks! (README explains a bit how)
