### ISSUE TITLE
Seed has no effect

### ISSUE THREAD

**Issue by fizaan** [remzi-arpacidusseau/ostep-homework#39]
cpu-intro/process-run.py

By supplying a seed, I get no effect - i.e. no random jobs/processes seem to be generated.

Expected behavior: random processes/jobs created based on seed supplied.

![image](https://user-images.githubusercontent.com/27024481/134029934-669eaa01-9cf5-4e56-b50e-d0a318db825b.png)

**Comment by remzi-arpacidusseau** [comment]
If the chance of doing a CPU instruction is 100%, seed will have no impact, that is correct....
