### ISSUE TITLE
Answer wanted

### ISSUE THREAD

**Issue by wangdake5111** [remzi-arpacidusseau/ostep-homework#4]
Are there any **correct answers** of the questions? I have some trouble dealing with them but don't know how. Thank you.

**Comment by remzi-arpacidusseau** [comment]
ha, good question.

Most simulators let you solve the question asked, e.g., with the "-c" flag. So in that sense, mostly. However, some broader "qualitative" questions are purposely left unanswered (and are for you to think about)....

hope that helps -
Remzi
